### ISSUE TITLE
Project Organisation

### ISSUE THREAD

**Issue by Benjymack** [ryangordon11235/Hangman#2]
It is my recommendation that you follow the common pattern for organising projects written in rust - an example would be https://github.com/Benjymack/orbit. You currently have a hangman folder inside your repository, however it is more typical for there to only be the src folder, with the Cargo.toml and other files in the root of the repository.

**Comment by ryangordon11235** [comment]
Thanks for the heads up, I'll fix that shortlyish.

**Comment by ryangordon11235** [comment]
Shortlyish is 6 days right :)
